# Generated by Django 5.1.3 on 2024-12-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livreaudio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='livres_audio/'),
        ),
    ]
